trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: UseNode@1
    displayName: "Install Node.js"
    inputs:
      version: "18.x"

  - script: |
      yarn install
    displayName: "Yarn install"

  - task: Bash@3
    inputs:
      targetType: "inline"
      script: "yarn cypress run"
    displayName: "Execução do testes de ponta a ponta (e2e)"
    continueOnError: true
